### ISSUE TITLE
Improve Readme of the project

### ISSUE THREAD

**Issue by Ayush7614** [edualgo/dsa-code-store#7]
We have to improve Readme of the project like contributers name project info and many things

**Comment by Ayush7614** [comment]
@Abhijit2505 plss assign me this issue

**Comment by Abhijit2505** [comment]
@Ayush7614 , this is just the code store for the **interview-corner** project. We are not going to promote this project as a DSA study guide. So there is no need of a good ReadME.

If you really want to add some README, you mat check the **interview-corner** repository.
