### ISSUE TITLE
Interview Questions on Array 

### ISSUE THREAD

**Issue by Ayush7614** [edualgo/dsa-code-store#8]
1 . duplicates in an array

2 . Sort an Array using Quicksort algorithm

**Comment by Ayush7614** [comment]
Like we have to add this questions in Array section of repository

**Comment by Ayush7614** [comment]
@Abhijit2505 plss review it and assigned to me so i have to work on this

**Comment by Abhijit2505** [comment]
@Ayush7614 open the same issue in the interview-corer repository
